### ISSUE TITLE
Hex encoding fails to generate leading zeros

### ISSUE THREAD

**Issue by quintesse** [codejive/java-properties#11]
```java
p.setProperty("test","الألبانية");
p.store(System.out);
```

Expected output: test=\u0627\u0644\u0623\u0644\u0628\u0627\u0646\u064a\u0629
Actual output: test=\u627\u644\u623\u644\u628\u627\u646\u64a\u629

**Comment by wilinz** [comment]
I've opened a new pull request, can you see?

**Comment by wilinz** [comment]
这是我的解决方案
```java
private String encodeUnicode(String raw) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            if (c > 0x7F) { //Escape non-ascii characters
                String hex = Integer.toHexString(c);
                if (hex.length() < 4) {
                    hex = String.format("%4s", hex).replace(" ", "0");
                }
                builder.append("\\u").append(hex);
            } else {
                builder.append(c);
            }
        }
        return builder.toString();
    }
```

**Comment by wilinz** [comment]
0x7F-0xFF should also be encoded, even if it is in the encoding range of ISO8859-1, otherwise sometimes the editor uses ASCII or utf-8 decoding to cause garbled characters

**Comment by quintesse** [comment]
> 0x7F-0xFF should also be encoded, even if it is in the encoding range of ISO8859-1, otherwise sometimes the editor uses ASCII or utf-8 decoding to cause garbled characters

I can understand that it can be a nuisance dealing with those characters in an editor, but I'm not sure I want to make that change. It might make _your_ life easier but for a large percentage of the world who use ISO8859-1 suddenly their files would change when loading and then saving again. I don't think that's acceptable. It would also change the behaviour of `org.codejive.properties.Properties` with respect to `java.util.Properties`.

**Comment by quintesse** [comment]
Ok, so I merged a PR that fixes the issue of not having 4 hex digits... but.... I'm rethinking how to handle UTF8.
