### ISSUE TITLE
The work is not correct if the newline character is \r+\n in properties file.

### ISSUE THREAD

**Issue by wls981** [codejive/java-properties#15]
The work is not correct if the newline character is \r+\n in properties file.

**Comment by quintesse** [comment]
Hi @wls981 , can you give an example of exactly what the problem is?

**Comment by wls981** [comment]
Hi, like this file. Thank you!
[properties-file.zip](https://github.com/codejive/java-properties/files/10002858/properties-file.zip)

**Comment by quintesse** [comment]
Thanks for the file. But can you tell me a bit what you're trying to do? Are you trying to read this file? Do you get an error or anything else?
